### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by dpriedel** [rianneogi/ide-cquery#16]
[Enter steps to reproduce:]

1.launch atom-ide native gdb debugger.

debugger launches and a pane full of garbage characters opens (it appears to be the executable file).

While the issue report points to atom-ide-ui package, they point to the cquery package based on the stack trace below.

**Atom**: 1.26.0 x64
**Electron**: 1.8.4
**OS**: "Manjaro Linux"
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.0

### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At /home/dpriedel/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:93

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1247:5)
    at server.disposable.add.atom.workspace.onDidChangeActiveTextEditor.editor (/packages/ide-cquery/lib/main.js:114:16)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:436:22)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:440:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at Workspace.open (/usr/lib/atom/src/workspace.js:1028:12)
    at <anonymous>
```

### Commands

```
     -8:13.1.0 core:confirm (input.hidden-input)
 10x -8:13.1.0 blur (input.hidden-input)
     -4:35.3.0 debugger:show-launch-dialog (input.hidden-input)
  2x -4:31.5.0 blur (input.hidden-input)
     -4:31.3.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -4:31.3.0 blur (button.btn.btn-primary)
     -4:31.3.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
  7x -4:31.2.0 blur (atom-pane.pane)
     -3:43.8.0 debugger:show-launch-dialog (input.hidden-input)
  3x -3:37 blur (input.hidden-input)
  2x -3:34.8.0 core:backspace (input.hidden-input)
  2x -3:32.1.0 blur (input.hidden-input)
     -3:31.8.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:31.8.0 blur (button.btn.btn-primary)
     -3:31.8.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
 10x -3:31.8.0 blur (atom-pane.pane)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ctags 5.1.2 
atom-eclipse-syntax 0.0.5 
atom-htmltidy 5.1.0 
atom-ide-debugger-native-gdb 0.7.1 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.11.0 
atom-visual-studio-code-light-ui 1.1.11 
atom-visual-studio-code-ui 1.3.4 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
build-cmake 0.11.0 
build-tools 4.5.12 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
data-atom 0.29.0 
editorconfig 2.2.2 
ex-mode 0.18.0 
foldername-tabs 0.2.4 
git-control 0.9.0 
git-diff-details 1.4.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gl-light-syntax 3.0.0 
gtk-dark-theme 0.1.4 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.6 
ide-cquery 0.10.0 
ide-json 0.2.1 
ide-python 0.9.2 
intentions 1.1.5 
language-antlr4 0.1.0 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-ipynb 1.3.0 
language-latex 1.1.1 
language-pgsql 0.2.3 
latex 0.50.0 
latex-plus 0.9.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
monokai 0.24.0 
pdf-view 0.69.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
scroll-sync 0.2.4 
seti-ui 1.10.0 
spacegray-light-neue-ui 0.1.7 
split-diff 1.5.2 
structure-view 0.2.1 
symbols-tree-nav 0.15.5 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-project-find-from-search 0.2.0 
you-complete-me 0.8.0 
```

**Comment by rianneogi** [comment]
Is it fixed in the new patch?

**Comment by dpriedel** [comment]
No.  I still get the same error even with the patched version of ide-cquery.
[Enter steps to reproduce:]

1. launch atom-ide native gdb debugger....
2. ...

**Atom**: 1.26.0 x64
**Electron**: 1.8.4
**OS**: "Manjaro Linux"
**Thrown From**: [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui) package 0.11.0


### Stack Trace

Uncaught TypeError: Path must be a string. Received null

```
At /home/dpriedel/.atom/packages/atom-ide-ui/node_modules/rxjs/bundles/Rx.min.js:93

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at Object.relative (path.js:1247:5)
    at server.disposable.add.atom.workspace.onDidChangeActiveTextEditor.editor (/packages/ide-cquery/lib/main.js:111:16)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/usr/lib/atom/src/workspace.js:436:22)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (/usr/lib/atom/src/workspace-center.js:17:14)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:141:28)
    at PaneContainer.didChangeActiveItemOnPane (/usr/lib/atom/src/pane-container.js:281:20)
    at Pane.setActiveItem (/usr/lib/atom/src/pane.js:440:42)
    at Pane.activateItem (/usr/lib/atom/src/pane.js:579:12)
    at Workspace.open (/usr/lib/atom/src/workspace.js:1028:12)
    at <anonymous>
```

### Commands

```
     -3:39.8.0 debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:36 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:35.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:20.7.0 debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:18.3.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -3:18.3.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -2:08.4.0 debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -2:06.5.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -2:06.4.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -1:54.3.0 window:toggle-dev-tools (atom-pane.pane.active)
     -0:56.4.0 debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:45 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:44.9.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:22.7.0 debugger:show-launch-dialog (input.hidden-input)
     -0:18.2.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -0:18.2.0 debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-ctags 5.1.2 
atom-eclipse-syntax 0.0.5 
atom-htmltidy 5.1.0 
atom-ide-debugger-native-gdb 0.7.1 
atom-ide-debugger-python 0.7.1 
atom-ide-ui 0.11.0 
atom-visual-studio-code-light-ui 1.1.11 
atom-visual-studio-code-ui 1.3.4 
autocomplete-python-jedi 1.10.3-0 
build 0.70.0 
build-cmake 0.11.0 
build-tools 4.5.12 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
data-atom 0.29.0 
editorconfig 2.2.2 
ex-mode 0.18.0 
foldername-tabs 0.2.4 
git-control 0.9.0 
git-diff-details 1.4.0 
git-status 0.3.4 
git-time-machine 1.5.9 
gl-light-syntax 3.0.0 
gtk-dark-theme 0.1.4 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
hydrogen-launcher 1.2.2 
hydrogen-python 0.0.6 
ide-cquery 0.11.0 
ide-json 0.2.1 
ide-python 0.9.2 
intentions 1.1.5 
language-antlr4 0.1.0 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-ipynb 1.3.0 
language-latex 1.1.1 
language-pgsql 0.2.3 
latex 0.50.0 
latex-plus 0.9.1 
linter 2.2.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
monokai 0.24.0 
pdf-view 0.69.0 
platformio-ide-terminal 2.8.1 
project-manager 3.3.5 
scroll-sync 0.2.4 
seti-ui 1.10.0 
spacegray-light-neue-ui 0.1.7 
split-diff 1.5.2 
structure-view 0.2.1 
symbols-tree-nav 0.15.5 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-project-find-from-search 0.2.0 
you-complete-me 0.8.0 
```

**Comment by edjubuh** [comment]
Are you familiar with the developer tools in Atom? I'm not able to reproduce the issue, and I'd like you to try one patch before publishing it.

**Comment by dpriedel** [comment]
A little familiar.

It will be a couple of hours before I can try this

thanks

**Comment by rianneogi** [comment]
The atom-ide-debugger doesn't seem to work for me, so I cannot debug this issue until I fix the debugger issue.

**Comment by dpriedel** [comment]
no problem.  let me know when you've got something you want me to try.

PS.  I had to install an older version of nodejs (v 7.1.0) to get the ide debugger to run.  I don't know if that's what you are running into...

**Comment by edjubuh** [comment]
Can you apply this diff to `/home/dpriedel/.atom/packages/ide-cquery/lib/main.js`:

```diff
diff --git a/lib/main.js b/lib/main.js
index 500fa39..70d3382 100644
--- a/lib/main.js
+++ b/lib/main.js
@@ -122,7 +122,8 @@ class CqueryLanguageClient extends AutoLanguageClient {
     let editor = atom.workspace.getActiveTextEditor();
     if(editor) {
       let paths = atom.project.relativizePath(editor.getPath());
-      if(!path.relative(paths[0], server.projectPath)) {
+	 console.log(paths);
+      if(paths[0] && !path.relative(paths[0], server.projectPath)) {
         server.connection.sendCustomRequest('$cquery/textDocumentDidView', {textDocumentUri: Convert.pathToUri(editor.getPath())});
       }
     }
```

(I'd recommend using the Human diff applier here 😃)

**Comment by dpriedel** [comment]
Will do...I'll need about 15 minutes...got to finish 1 thing.

**Comment by dpriedel** [comment]
I've applied the patch...what should I look for?

**Comment by edjubuh** [comment]
Does it still throw the exception? You can look at the developer tools as well to see what the `paths` array is.

**Comment by dpriedel** [comment]
Yes, it still throws in the same place.
the paths array has 2 elements:
- the full path to my project directory
- the leaf name of the file I am trying to debug.

I don't seem to be able to copy/paste the console content...

**Comment by edjubuh** [comment]
Can you add `console.log(server.projectPath)`, I suppose

**Comment by dpriedel** [comment]
Here's what I've got for the array values

0: "/home/dpriedel/projects/github/ExtractEDGAR_XBRL_Test"
1: "Unit_Test.cpp"

**Comment by dpriedel** [comment]
this seems to fix the problem.

change line 111 of main.js

from:
if(!path.relative(paths[0], server.projectPath)) {

to:
if(paths[0] && !path.relative(paths[0], server.projectPath)) {

after making this change, I can debug with no problems.

**Comment by rianneogi** [comment]
Thanks! I pushed a new patch with the change.
